name: versystems_app
description: "A new Flutter project."
publish_to: 'none' 
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    # Regras de qualidade de código
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Regras de performance
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    
    # Regras de segurança
    avoid_dynamic_calls: true
    avoid_type_to_string: true

version: 1.0.0+1

environment:
  sdk: ^3.11.0
flutter_gen:
  output: lib/config/helpers/gen/

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  excel:
    path: ../excel
  fx_ui:
    path: ../fx_ui
  cupertino_icons: ^1.0.8
  shadcn_flutter: ^0.0.53
  get: ^4.7.3
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  validatorless: ^1.2.5
  material_symbols_icons: ^4.2906.0
  lucide_icons_flutter: ^3.1.9
  firebase_storage: ^13.1.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_functions: ^6.0.6
  cloud_firestore: ^6.1.2
  image: ^4.5.4
  web: ^1.1.1
  pdf: ^3.11.3
  uuid: ^4.5.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  camera: ^0.12.0+2
  file_picker: ^12.0.0-beta.7
  signature: ^6.3.0
  image_picker: ^1.2.1
  printing: ^5.14.2
  mask_text_input_formatter: ^2.9.0
  dev: ^1.0.0
  flutter_gen: ^5.12.0
  package_info_plus: ^10.2.1
  geolocator: ^14.0.3
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.12.0

  flutter_lints: ^6.0.0
  build_runner: ^2.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/common/lists/
    - assets/images/common/logos/
    - assets/images/common/upload/
    - assets/images/views/login/
    - assets/files/
  fonts:
    - family: Roboto # Here
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
